# Generated by Django 3.0.3 on 2020-05-21 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('friendly_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_in_days', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=False, unique=True)),
                ('available', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('trial_days', models.PositiveIntegerField(default=None, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 10, 30, 55, 846769, tzinfo=utc))),
                ('url', models.URLField(blank=True)),
                ('customized', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.DO_NOTHING, to='plans.Currency')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Period')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_boolean', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 10, 30, 55, 849290, tzinfo=utc))),
                ('expires_at', models.DateField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_automatic_renewal', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('plan_period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plans.PlanPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=None, max_length=255)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plans.PaymentMethod')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plans.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='PlanQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=1, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Quota')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='quotas',
            field=models.ManyToManyField(through='plans.PlanQuota', to='plans.Quota'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 10, 30, 55, 851106, tzinfo=utc))),
                ('date_completed', models.DateTimeField(null=True)),
                ('plan_extended_from', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 10, 30, 55, 851137, tzinfo=utc))),
                ('plan_extended_until', models.DateTimeField(default=datetime.datetime(2020, 6, 20, 10, 30, 55, 851151, tzinfo=utc))),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.IntegerField(choices=[(1, 'NEW'), (2, 'COMPLETED'), (3, 'NOT_VALID'), (4, 'CANCELED'), (5, 'RETURNED')], default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Account')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plans.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('full_number', models.CharField(max_length=200)),
                ('issued', models.DateField(db_index=True)),
                ('payment_date', models.DateField(db_index=True)),
                ('unit_price_net', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField(default=1)),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=4, null=True)),
                ('rebate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_street', models.CharField(max_length=200)),
                ('buyer_zipcode', models.CharField(max_length=200)),
                ('buyer_city', models.CharField(max_length=200)),
                ('buyer_country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('buyer_tax_number', models.CharField(blank=True, max_length=200)),
                ('shipping_name', models.CharField(max_length=200)),
                ('shipping_street', models.CharField(max_length=200)),
                ('shipping_zipcode', models.CharField(max_length=200)),
                ('shipping_city', models.CharField(max_length=200)),
                ('shipping_country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('require_shipment', models.BooleanField(db_index=True, default=False)),
                ('issuer_name', models.CharField(max_length=200)),
                ('issuer_street', models.CharField(max_length=200)),
                ('issuer_zipcode', models.CharField(max_length=200)),
                ('issuer_city', models.CharField(max_length=200)),
                ('issuer_country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('issuer_tax_number', models.CharField(blank=True, max_length=200, verbose_name='TAX/VAT number')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Account')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plans.Order')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
