# Generated by Django 3.0.3 on 2020-05-21 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_cancelled', models.DateTimeField(null=True)),
                ('date_updated', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('is_channel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=100)),
                ('facebook_page_id', models.CharField(max_length=100)),
                ('facebook_ads_id', models.CharField(max_length=100)),
                ('instagram_id', models.CharField(max_length=100)),
                ('instagram_ads_id', models.CharField(max_length=100)),
                ('messenger', models.BooleanField(default=True)),
                ('enable_instagram_comments', models.BooleanField(default=True)),
                ('enable_fb_posts_comments', models.BooleanField(default=True)),
                ('enable_instagram_ads', models.BooleanField(default=True)),
                ('import_history', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('messenger_code', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_disabled', models.DateTimeField(null=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.Integration')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('is_gmail_integration', models.BooleanField(default=True)),
                ('is_outlook_integration', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('internal_email', models.CharField(max_length=100, unique=True)),
                ('leave_mail_on_server', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_disabled', models.DateTimeField(null=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.Integration')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro_text_business_hours', models.CharField(max_length=1000)),
                ('intro_text_off_hours', models.CharField(max_length=1000)),
                ('use_image', models.BooleanField(default=True)),
                ('use_logo', models.BooleanField(default=True)),
                ('header_color', models.CharField(default='#172a72', max_length=7)),
                ('chat_color', models.CharField(default='#172a72', max_length=7)),
                ('javascript_snippet', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_disabled', models.DateTimeField(null=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.Integration')),
            ],
        ),
        migrations.AddField(
            model_name='integration',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='integrations.IntegrationType'),
        ),
    ]
