# Generated by Django 3.0.3 on 2020-05-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationtype',
            name='description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationtype',
            name='name',
            field=models.CharField(default='Email', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationtype',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationtype',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
