# Generated by Django 3.0.3 on 2020-05-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200522_0819'),
        ('integrations', '0002_auto_20200522_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
            preserve_default=False,
        ),
    ]
