# Generated by Django 3.0.3 on 2020-05-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsettings_account'),
        ('integrations', '0003_integration_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
