# Generated by Django 3.0.3 on 2020-05-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20200522_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
