# Generated by Django 3.0.3 on 2020-05-22 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_auto_20200522_0730'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
        migrations.AddField(
            model_name='attachment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='message',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_messages', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='message',
            name='body_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.Ticket'),
        ),
        migrations.AddField(
            model_name='note',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_tickets', to='tickets.Ticket'),
        ),
        migrations.AddField(
            model_name='tag',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_tickets', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='tickets.Attachment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='canned_response_used',
            field=models.ManyToManyField(blank=True, to='tickets.CannedResponse'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_through',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_failed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_address',
            field=models.ManyToManyField(blank=True, related_name='from_address', to='tickets.AddressInfo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.Integration'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mail_headers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='reason_for_failure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='rule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='signature_used',
            field=models.ManyToManyField(blank=True, to='users.Signature'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_address',
            field=models.ManyToManyField(blank=True, related_name='to_address', to='tickets.AddressInfo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_team_tickets', to='users.Team'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='integrations.Integration'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tickets.Tag'),
        ),
    ]
