# Generated by Django 3.0.3 on 2020-05-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200522_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes_tickets', to='tickets.Ticket'),
            preserve_default=False,
        ),
    ]
