# Generated by Django 3.0.3 on 2020-05-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsettings_account'),
        ('tickets', '0008_auto_20200522_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_accounts', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.Ticket'),
        ),
    ]
