# Generated by Django 3.0.3 on 2020-05-22 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='domain',
            field=models.CharField(default='abc.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='name',
            field=models.CharField(default='ss', max_length=100),
            preserve_default=False,
        ),
    ]
