# Generated by Django 3.0.3 on 2020-05-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200522_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_suspended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
