# Generated by Django 3.0.3 on 2020-05-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200522_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
            preserve_default=False,
        ),
    ]
