# Generated by Django 3.0.6 on 2020-05-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsettings_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_suspended',
        ),
    ]
